fixtures:
  repositories:
    php: git://github.com/saz/puppet-php.git
    apt: git://github.com/puppetlabs/puppetlabs-apt.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    bazinga: "#{source_dir}"
