fixtures:
  repositories:
    apache: git://github.com/puppetlabs/puppetlabs-apache.git
    apt: git://github.com/puppetlabs/puppetlabs-apt.git
    composer: git://github.com/willdurand/puppet-composer.git
    ntp: git://github.com/saz/puppet-ntp.git
    php: git://github.com/saz/puppet-php.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    bazinga: "#{source_dir}"
