language: ruby

rvm:
  - 1.8.7
  - 1.9.3

env:
  matrix:
    - PUPPET_VERSION="~> 2.7.0"
    - PUPPET_VERSION="~> 3.1.0"
    - PUPPET_VERSION="~> 3.2.0"
    - PUPPET_VERSION="~> 3.3.0"

script: "rake test"

gemfile: .gemfile
