name        'willdurand-bazinga'
version '0.0.14'
summary     'This module contains a set of roles and some useful functions.'
description 'This module contains a set of roles and some useful functions.'
license     'MIT'
author      'William Durand'

dependency  'puppetlabs/apt'
dependency  'puppetlabs/stdlib'
dependency  'saz/ntp'
